name: album_filmes_app
description: "Seu album de filmes pessoal!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  firebase_auth: ^5.5.2
  google_fonts: ^6.2.1
  provider: ^6.1.4
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  flutter_screenutil : ^5.9.3
  cached_network_image: ^3.2.0
  scrollable_positioned_list: ^0.3.5
  flutter_rating_bar: ^4.0.1
  scratcher: ^2.5.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_tiny.png
    - assets/.env

